<<<<<<< HEAD
=======
# Generated by Django 5.0.1 on 2026-03-11 17:20

>>>>>>> f9d423aefd9f5610453da9d3d9140355b74c3b0b
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
