# Generated by Django 5.0.1 on 2026-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_order_user_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(blank=True, help_text='Product code (101-200)', null=True, unique=True),
        ),
    ]
