# Generated by Django 5.0.1 on 2026-03-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_poster_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
