# Generated by Django 5.0.1 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_merge_0009_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Length in millimeters', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Width in millimeters', null=True),
        ),
    ]
