# Generated by Django 5.0.1 on 2026-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_product_finish_and_finish_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['gmt_code', 'name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(blank=True, help_text='Product code (101-400)', null=True, unique=True),
        ),
    ]
