# Generated by Django 5.0.1 on 2026-05-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_discount_order_discount_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
